--Add通知记录
CREATE TABLE IF NOT EXISTS tongzhi_record (
  id BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  tongzhi_id BIGINT(20) NULL DEFAULT NULL COMMENT '通知ID',
  tongzhibianhao VARCHAR(200) NULL DEFAULT NULL COMMENT '通知编号',
  zhanghao VARCHAR(200) NULL DEFAULT NULL COMMENT '账号',
  shouji VARCHAR(200) NULL DEFAULT NULL COMMENT '手机',
  tongzhineirong TEXT NULL COMMENT '通知内容',
  fasongshijian DATETIME NULL DEFAULT NULL COMMENT '发送时间',
  fasongzhuangtai VARCHAR(20) NULL DEFAULT NULL COMMENT '发送状态：成功、失败',
  shibaiyuanyin VARCHAR(500) NULL DEFAULT NULL COMMENT '失败原因',
  chongcishu INT(11) DEFAULT 0 COMMENT '重试次数',
  addtime DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '添加时间',
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='通知发送记录';
